=== stillwaiting/emptybars/common-ts/model/v0001/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1610084225.json",
  "title": "Root",
  "type": "object",
  "required": [
    "sections",
    "videoUrl",
    "version",
    "pageUrls"
  ],
  "properties": {
    "sections": {
      "$id": "#root/sections",
      "title": "Sections",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/sections/items",
        "title": "Items",
        "type": "object",
        "required": [
          "pages",
          "pageAreas",
          "start",
          "end"
        ],
        "properties": {
          "pages": {
            "$id": "#root/sections/items/pages",
            "title": "Pages",
            "type": "array",
            "default": [],
            "items":{
              "$id": "#root/sections/items/pages/items",
              "title": "Items",
              "type": "integer",
              "examples": [
                0
              ],
              "default": 0
            }
          },
          "pageAreas": {
            "$id": "#root/sections/items/pageAreas",
            "title": "Pageareas",
            "type": "array",
            "default": [],
            "items":{
              "$id": "#root/sections/items/pageAreas/items",
              "title": "Items",
              "type": "object",
              "required": [
                "pageIdx",
                "areas"
              ],
              "properties": {
                "pageIdx": {
                  "$id": "#root/sections/items/pageAreas/items/pageIdx",
                  "title": "Pageidx",
                  "type": "integer",
                  "examples": [
                    0
                  ],
                  "default": 0
                },
                "areas": {
                  "$id": "#root/sections/items/pageAreas/items/areas",
                  "title": "Areas",
                  "type": "array",
                  "default": [],
                  "items":{
                    "$id": "#root/sections/items/pageAreas/items/areas/items",
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "x",
                      "y",
                      "width",
                      "height"
                    ],
                    "properties": {
                      "x": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/x",
                        "title": "X",
                        "type": "integer",
                        "examples": [
                          753
                        ],
                        "default": 0
                      },
                      "y": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/y",
                        "title": "Y",
                        "type": "integer",
                        "examples": [
                          169
                        ],
                        "default": 0
                      },
                      "width": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/width",
                        "title": "Width",
                        "type": "integer",
                        "examples": [
                          -724
                        ],
                        "default": 0
                      },
                      "height": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/height",
                        "title": "Height",
                        "type": "integer",
                        "examples": [
                          -171
                        ],
                        "default": 0
                      }
                    }
                  }

                }
              }
            }

          },
          "start": {
            "$id": "#root/sections/items/start",
            "title": "Start",
            "type": "string",
            "default": "",
            "examples": [
              "04:00.3"
            ],
            "pattern": "^[0-9]{2,}:[0-9]{2}\\.?[0-9]?$"
          },
          "end": {
            "$id": "#root/sections/items/end",
            "title": "End",
            "type": "string",
            "default": "",
            "examples": [
              "04:07.9"
            ],
            "pattern": "^[0-9]{2,}:[0-9]{2}\\.?[0-9]?$"
          }
        }
      }

    },
    "videoUrl": {
      "$id": "#root/videoUrl",
      "title": "Videourl",
      "type": "string",
      "default": "",
      "examples": [
        "https://www.youtube.com/watch?v=aTopxwu1KUE"
      ],
      "pattern": "^https?://.*$"
    },
    "version": {
      "$id": "#root/version",
      "title": "Version",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "pageUrls": {
      "$id": "#root/pageUrls",
      "title": "Pageurls",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/pageUrls/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "examples": [
          "https://images2.imgbox.com/f8/2b/l64abGMR_o.jpg?download=true"
        ],
        "pattern": "^https?://.*$"
      }
    }
  }
}

=== stillwaiting/emptybars/composers/debussy/childrens-corner-1-doctor/crossley/sections.json
{
  "sections": [
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 200,
              "y": 377,
              "width": 1295,
              "height": 401
            },
            {
              "x": 10,
              "y": 850,
              "width": 190,
              "height": 377
            }
          ]
        }
      ],
      "start": "00:0.9",
      "end": "00:4.7"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 0,
              "y": 822,
              "width": 1496,
              "height": 421
            },
            {
              "x": 17,
              "y": 1275,
              "width": 537,
              "height": 459
            }
          ]
        }
      ],
      "start": "00:4.3",
      "end": "00:11.6"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 550,
              "y": 1302,
              "width": 945,
              "height": 414
            },
            {
              "x": 10,
              "y": 1798,
              "width": 1003,
              "height": 374
            }
          ]
        }
      ],
      "start": "00:11.7",
      "end": "00:17.8"
    },
    {
      "pages": [
        0,
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 996,
              "y": 1795,
              "width": 605,
              "height": 401
            }
          ]
        },
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 13,
              "y": 244,
              "width": 343,
              "height": 329
            }
          ]
        }
      ],
      "start": "00:17.7",
      "end": "00:20.7"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 353,
              "y": 210,
              "width": 1156,
              "height": 370
            },
            {
              "x": 40,
              "y": 649,
              "width": 992,
              "height": 319
            }
          ]
        }
      ],
      "start": "00:20.7",
      "end": "00:26.7"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 1023,
              "y": 639,
              "width": 520,
              "height": 326
            },
            {
              "x": 10,
              "y": 1064,
              "width": 1570,
              "height": 323
            },
            {
              "x": 17,
              "y": 1417,
              "width": 581,
              "height": 363
            }
          ]
        }
      ],
      "start": "00:26.6",
      "end": "00:35.3"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 605,
              "y": 1441,
              "width": 928,
              "height": 319
            },
            {
              "x": 20,
              "y": 1832,
              "width": 159,
              "height": 360
            }
          ]
        }
      ],
      "start": "00:35.3",
      "end": "00:39.6"
    },
    {
      "pages": [
        1,
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 20,
              "y": 1819,
              "width": 1513,
              "height": 377
            }
          ]
        },
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 3,
              "y": 207,
              "width": 1547,
              "height": 377
            },
            {
              "x": 27,
              "y": 605,
              "width": 1499,
              "height": 370
            }
          ]
        }
      ],
      "start": "00:39.1",
      "end": "00:58.6"
    },
    {
      "pages": [
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 30,
              "y": 989,
              "width": 1455,
              "height": 367
            }
          ]
        }
      ],
      "start": "00:58.6",
      "end": "01:10.4"
    },
    {
      "pages": [
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 1526,
              "y": 2186,
              "width": -1516,
              "height": -765
            }
          ]
        }
      ],
      "start": "01:10.4",
      "end": "01:28.4"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 6,
              "y": 207,
              "width": 1196,
              "height": 414
            }
          ]
        }
      ],
      "start": "01:28.4",
      "end": "01:32.7"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 1098,
              "y": 255,
              "width": 476,
              "height": 387
            },
            {
              "x": 20,
              "y": 652,
              "width": 1526,
              "height": 387
            }
          ]
        }
      ],
      "start": "01:32.4",
      "end": "01:39.8"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 20,
              "y": 1047,
              "width": 1519,
              "height": 333
            },
            {
              "x": 10,
              "y": 1428,
              "width": 581,
              "height": 316
            }
          ]
        }
      ],
      "start": "01:39.8",
      "end": "01:45.8"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 598,
              "y": 1424,
              "width": 958,
              "height": 336
            }
          ]
        }
      ],
      "start": "01:45.8",
      "end": "01:49.1"
    },
    {
      "pages": [
        3,
        4
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 1455,
              "y": 1451,
              "width": 102,
              "height": 319
            },
            {
              "x": 20,
              "y": 1812,
              "width": 1536,
              "height": 367
            }
          ]
        },
        {
          "pageIdx": 4,
          "areas": [
            {
              "x": 10,
              "y": 224,
              "width": 1526,
              "height": 353
            },
            {
              "x": 27,
              "y": 595,
              "width": 1020,
              "height": 357
            }
          ]
        }
      ],
      "start": "01:48.8",
      "end": "02:0.3"
    },
    {
      "pages": [
        4
      ],
      "pageAreas": [
        {
          "pageIdx": 4,
          "areas": [
            {
              "x": 1050,
              "y": 595,
              "width": 489,
              "height": 363
            },
            {
              "x": 3,
              "y": 982,
              "width": 564,
              "height": 350
            }
          ]
        }
      ],
      "start": "02:0.3",
      "end": "02:3.6"
    },
    {
      "pages": [
        4
      ],
      "pageAreas": [
        {
          "pageIdx": 4,
          "areas": [
            {
              "x": 571,
              "y": 975,
              "width": 962,
              "height": 360
            },
            {
              "x": 13,
              "y": 1356,
              "width": 1030,
              "height": 401
            }
          ]
        }
      ],
      "start": "02:3.6",
      "end": "02:8.7"
    },
    {
      "pages": [
        4
      ],
      "pageAreas": [
        {
          "pageIdx": 4,
          "areas": [
            {
              "x": 802,
              "y": 1523,
              "width": 0,
              "height": 0
            },
            {
              "x": 1037,
              "y": 1377,
              "width": 510,
              "height": 391
            },
            {
              "x": 37,
              "y": 1754,
              "width": 1468,
              "height": 377
            }
          ]
        }
      ],
      "start": "02:8.8",
      "end": "02:19.9"
    }
  ],
  "videoUrl": "https://www.youtube.com/watch?v=1k_OLrK4ZuE",
  "version": 1,
  "pageUrls": [
    "https://images2.imgbox.com/4b/6a/HmnudZ9o_o.jpg?download=true",
    "https://images2.imgbox.com/13/34/zq9gm8Lo_o.jpg?download=true",
    "https://images2.imgbox.com/c3/f6/Tvjo7ahq_o.jpg?download=true",
    "https://images2.imgbox.com/95/2f/oph4GdmY_o.jpg?download=true",
    "https://images2.imgbox.com/56/8e/QbKPtioq_o.jpg?download=true"
  ]
}

=== stillwaiting/emptybars/composers/c418/wet-hands/c418/sections.json
{
  "sections": [
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 121,
              "y": 199,
              "width": 1073,
              "height": 320
            }
          ]
        }
      ],
      "start": "00:01.0",
      "end": "00:14.0"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1219,
              "y": 224,
              "width": 262,
              "height": 286
            },
            {
              "x": 90,
              "y": 526,
              "width": 863,
              "height": 299
            }
          ]
        }
      ],
      "start": "00:14.0",
      "end": "00:26.5"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 941,
              "y": 548,
              "width": 558,
              "height": 305
            },
            {
              "x": 63,
              "y": 850,
              "width": 552,
              "height": 320
            }
          ]
        }
      ],
      "start": "00:26.5",
      "end": "00:39.3"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 611,
              "y": 893,
              "width": 872,
              "height": 271
            },
            {
              "x": 50,
              "y": 1192,
              "width": 299,
              "height": 289
            }
          ]
        }
      ],
      "start": "00:39.3",
      "end": "00:53.9"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 349,
              "y": 1217,
              "width": 872,
              "height": 259
            }
          ]
        }
      ],
      "start": "00:53.9",
      "end": "01:07.8"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1219,
              "y": 1189,
              "width": 289,
              "height": 299
            },
            {
              "x": 109,
              "y": 1501,
              "width": 397,
              "height": 323
            },
            {
              "x": 497,
              "y": 1498,
              "width": 986,
              "height": 348
            }
          ]
        }
      ],
      "start": "01:07.8",
      "end": "01:28.9"
    }
  ],
  "videoUrl": "https://www.youtube.com/watch?v=mukiMaOSLEs",
  "version": 1,
  "pageUrls": [
    "https://images2.imgbox.com/23/43/aHKTQRMr_o.png?download=true"
  ]
}

=== stillwaiting/emptybars/composers/bach/goldberg-v-01/schiff/sections.json
{
  "sections": [
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 753,
              "y": 169,
              "width": -724,
              "height": -171
            },
            {
              "x": 14,
              "y": 209,
              "width": 234,
              "height": 176
            }
          ]
        }
      ],
      "start": "04:00.3",
      "end": "04:07.9"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 250,
              "y": 208,
              "width": 509,
              "height": 164
            },
            {
              "x": 25,
              "y": 387,
              "width": 285,
              "height": 173
            }
          ]
        }
      ],
      "start": "04:07.9",
      "end": "04:14.4"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 312,
              "y": 397,
              "width": 447,
              "height": 179
            },
            {
              "x": 0,
              "y": 565,
              "width": 527,
              "height": 181
            }
          ]
        }
      ],
      "start": "04:14.4",
      "end": "04:22.9"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 502,
              "y": 599,
              "width": 256,
              "height": 147
            },
            {
              "x": 6,
              "y": 777,
              "width": 740,
              "height": 173
            }
          ]
        }
      ],
      "start": "04:22.6",
      "end": "04:29.7"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 58,
              "y": 4,
              "width": 701,
              "height": 196
            },
            {
              "x": 11,
              "y": 199,
              "width": 237,
              "height": 179
            }
          ]
        }
      ],
      "start": "04:29.7",
      "end": "04:36.8"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 253,
              "y": 212,
              "width": 507,
              "height": 168
            },
            {
              "x": 3,
              "y": 384,
              "width": 311,
              "height": 168
            }
          ]
        }
      ],
      "start": "04:36.8",
      "end": "04:42.9"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 309,
              "y": 386,
              "width": 447,
              "height": 187
            },
            {
              "x": 11,
              "y": 578,
              "width": 520,
              "height": 184
            }
          ]
        }
      ],
      "start": "04:42.9",
      "end": "04:51.4"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 508,
              "y": 594,
              "width": 242,
              "height": 156
            },
            {
              "x": 9,
              "y": 777,
              "width": 733,
              "height": 187
            }
          ]
        }
      ],
      "start": "04:51.2",
      "end": "04:58.3"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 37,
              "y": 7,
              "width": 725,
              "height": 179
            },
            {
              "x": 6,
              "y": 205,
              "width": 220,
              "height": 185
            }
          ]
        }
      ],
      "start": "04:58.3",
      "end": "05:05.4"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 224,
              "y": 197,
              "width": 538,
              "height": 182
            },
            {
              "x": 11,
              "y": 377,
              "width": 483,
              "height": 206
            }
          ]
        }
      ],
      "start": "05:05.4",
      "end": "05:12.5"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 522,
              "y": 401,
              "width": 243,
              "height": 155
            },
            {
              "x": 9,
              "y": 563,
              "width": 759,
              "height": 168
            },
            {
              "x": 499,
              "y": 405,
              "width": 32,
              "height": 142
            }
          ]
        }
      ],
      "start": "05:12.5",
      "end": "05:19.8"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 8,
              "y": 780,
              "width": 755,
              "height": 185
            }
          ]
        }
      ],
      "start": "05:19.8",
      "end": "05:26.9"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 768,
              "y": 178,
              "width": -761,
              "height": -179
            },
            {
              "x": 5,
              "y": 189,
              "width": 217,
              "height": 188
            }
          ]
        }
      ],
      "start": "05:26.9",
      "end": "05:33.9"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 534,
              "y": 401,
              "width": -537,
              "height": 177
            },
            {
              "x": 768,
              "y": 373,
              "width": -562,
              "height": -169
            }
          ]
        }
      ],
      "start": "05:33.9",
      "end": "05:40.8"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 544,
              "y": 405,
              "width": 226,
              "height": 146
            },
            {
              "x": 0,
              "y": 567,
              "width": 764,
              "height": 177
            }
          ]
        }
      ],
      "start": "05:40.8",
      "end": "05:48.2"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 11,
              "y": 777,
              "width": 751,
              "height": 180
            }
          ]
        }
      ],
      "start": "05:48.2",
      "end": "05:56.0"
    }
  ],
  "videoUrl": "https://www.youtube.com/watch?v=aTopxwu1KUE",
  "version": 1,
  "pageUrls": [
    "https://images2.imgbox.com/f8/2b/l64abGMR_o.jpg?download=true",
    "https://images2.imgbox.com/3b/1c/UsutTWGB_o.jpg?download=true"
  ]
}
