=== stillwaiting/emptybars/common-ts/model/v0001/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1610084225.json",
  "title": "Root",
  "type": "object",
  "required": [
    "sections",
    "videoUrl",
    "version",
    "pageUrls"
  ],
  "properties": {
    "sections": {
      "$id": "#root/sections",
      "title": "Sections",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/sections/items",
        "title": "Items",
        "type": "object",
        "required": [
          "pages",
          "pageAreas",
          "start",
          "end"
        ],
        "properties": {
          "pages": {
            "$id": "#root/sections/items/pages",
            "title": "Pages",
            "type": "array",
            "default": [],
            "items":{
              "$id": "#root/sections/items/pages/items",
              "title": "Items",
              "type": "integer",
              "examples": [
                0
              ],
              "default": 0
            }
          },
          "pageAreas": {
            "$id": "#root/sections/items/pageAreas",
            "title": "Pageareas",
            "type": "array",
            "default": [],
            "items":{
              "$id": "#root/sections/items/pageAreas/items",
              "title": "Items",
              "type": "object",
              "required": [
                "pageIdx",
                "areas"
              ],
              "properties": {
                "pageIdx": {
                  "$id": "#root/sections/items/pageAreas/items/pageIdx",
                  "title": "Pageidx",
                  "type": "integer",
                  "examples": [
                    0
                  ],
                  "default": 0
                },
                "areas": {
                  "$id": "#root/sections/items/pageAreas/items/areas",
                  "title": "Areas",
                  "type": "array",
                  "default": [],
                  "items":{
                    "$id": "#root/sections/items/pageAreas/items/areas/items",
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "x",
                      "y",
                      "width",
                      "height"
                    ],
                    "properties": {
                      "x": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/x",
                        "title": "X",
                        "type": "integer",
                        "examples": [
                          753
                        ],
                        "default": 0
                      },
                      "y": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/y",
                        "title": "Y",
                        "type": "integer",
                        "examples": [
                          169
                        ],
                        "default": 0
                      },
                      "width": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/width",
                        "title": "Width",
                        "type": "integer",
                        "examples": [
                          -724
                        ],
                        "default": 0
                      },
                      "height": {
                        "$id": "#root/sections/items/pageAreas/items/areas/items/height",
                        "title": "Height",
                        "type": "integer",
                        "examples": [
                          -171
                        ],
                        "default": 0
                      }
                    }
                  }

                }
              }
            }

          },
          "start": {
            "$id": "#root/sections/items/start",
            "title": "Start",
            "type": "string",
            "default": "",
            "examples": [
              "04:00.3"
            ],
            "pattern": "^[0-9]{2,}:[0-9]{2}\\.?[0-9]?$"
          },
          "end": {
            "$id": "#root/sections/items/end",
            "title": "End",
            "type": "string",
            "default": "",
            "examples": [
              "04:07.9"
            ],
            "pattern": "^[0-9]{2,}:[0-9]{2}\\.?[0-9]?$"
          }
        }
      }

    },
    "videoUrl": {
      "$id": "#root/videoUrl",
      "title": "Videourl",
      "type": "string",
      "default": "",
      "examples": [
        "https://www.youtube.com/watch?v=aTopxwu1KUE"
      ],
      "pattern": "^https?://.*$"
    },
    "version": {
      "$id": "#root/version",
      "title": "Version",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "pageUrls": {
      "$id": "#root/pageUrls",
      "title": "Pageurls",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/pageUrls/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "examples": [
          "https://images2.imgbox.com/f8/2b/l64abGMR_o.jpg?download=true"
        ],
        "pattern": "^https?://.*$"
      }
    }
  }
}

=== stillwaiting/emptybars/composers/nahre-sol/solitude/nahre-sol/sections.json
{
  "sections": [
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 139,
              "y": 295,
              "width": 1479,
              "height": 455
            },
            {
              "x": 132,
              "y": 782,
              "width": 503,
              "height": 384
            }
          ]
        }
      ],
      "start": "00:1.1",
      "end": "00:21.3"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 646,
              "y": 829,
              "width": 941,
              "height": 343
            },
            {
              "x": 125,
              "y": 1217,
              "width": 333,
              "height": 357
            }
          ]
        }
      ],
      "start": "00:21.3",
      "end": "00:37.3"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 459,
              "y": 1254,
              "width": 1088,
              "height": 346
            }
          ]
        }
      ],
      "start": "00:37.3",
      "end": "00:53.7"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1540,
              "y": 1275,
              "width": 71,
              "height": 285
            },
            {
              "x": 136,
              "y": 1672,
              "width": 911,
              "height": 401
            }
          ]
        }
      ],
      "start": "00:53.7",
      "end": "01:5.3"
    },
    {
      "pages": [
        0,
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1040,
              "y": 1706,
              "width": 591,
              "height": 336
            }
          ]
        },
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 146,
              "y": 146,
              "width": 1281,
              "height": 353
            }
          ]
        }
      ],
      "start": "01:5.3",
      "end": "01:29.6"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 1421,
              "y": 166,
              "width": 200,
              "height": 367
            },
            {
              "x": 108,
              "y": 537,
              "width": 1509,
              "height": 384
            }
          ]
        }
      ],
      "start": "01:29.6",
      "end": "01:54.1"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 71,
              "y": 958,
              "width": 1547,
              "height": 346
            },
            {
              "x": 105,
              "y": 1319,
              "width": 1496,
              "height": 428
            }
          ]
        }
      ],
      "start": "01:54.1",
      "end": "02:34.8"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 108,
              "y": 1706,
              "width": 1509,
              "height": 428
            }
          ]
        }
      ],
      "start": "02:34.0",
      "end": "03:6.5"
    }
  ],
  "videoUrl": "https://www.youtube.com/watch?v=hj1vJ-cNfaE",
  "version": 1,
  "pageUrls": [
    "https://images2.imgbox.com/57/a1/3MThQXK1_o.jpg?download=true",
    "https://images2.imgbox.com/00/34/EwrHS1xW_o.jpg?download=true"
  ]
}

=== stillwaiting/emptybars/composers/debussy/preludes-1-08-flaxen-hair/michelangeli/sections.json
{
  "sections": [
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 346,
              "y": 304,
              "width": 1341,
              "height": 435
            }
          ]
        }
      ],
      "start": "00:13.5",
      "end": "00:27.0"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1687,
              "y": 399,
              "width": 182,
              "height": 344
            },
            {
              "x": 160,
              "y": 735,
              "width": 843,
              "height": 395
            }
          ]
        }
      ],
      "start": "00:27.0",
      "end": "00:37.0"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1003,
              "y": 731,
              "width": 850,
              "height": 427
            },
            {
              "x": 140,
              "y": 1151,
              "width": 847,
              "height": 415
            }
          ]
        }
      ],
      "start": "00:37.0",
      "end": "00:54.1"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 987,
              "y": 1158,
              "width": 664,
              "height": 431
            }
          ]
        }
      ],
      "start": "00:54.1",
      "end": "01:03.1"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1664,
              "y": 1178,
              "width": 193,
              "height": 407
            },
            {
              "x": 144,
              "y": 1578,
              "width": 969,
              "height": 498
            }
          ]
        }
      ],
      "start": "01:03.1",
      "end": "01:09.3"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1113,
              "y": 1590,
              "width": 688,
              "height": 486
            }
          ]
        }
      ],
      "start": "01:09.3",
      "end": "01:15.4"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 164,
              "y": 2002,
              "width": 1219,
              "height": 486
            }
          ]
        }
      ],
      "start": "01:15.4",
      "end": "01:25.0"
    },
    {
      "pages": [
        0,
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1394,
              "y": 2049,
              "width": 443,
              "height": 455
            }
          ]
        },
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 160,
              "y": 106,
              "width": 257,
              "height": 474
            }
          ]
        }
      ],
      "start": "01:25.0",
      "end": "01:28.5"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 409,
              "y": 125,
              "width": 478,
              "height": 459
            }
          ]
        }
      ],
      "start": "01:28.5",
      "end": "01:31.2"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 900,
              "y": 70,
              "width": 961,
              "height": 506
            },
            {
              "x": 152,
              "y": 545,
              "width": 621,
              "height": 490
            }
          ]
        }
      ],
      "start": "01:31.2",
      "end": "01:43.1"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 753,
              "y": 592,
              "width": 692,
              "height": 423
            }
          ]
        }
      ],
      "start": "01:43.1",
      "end": "01:50.9"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 1454,
              "y": 588,
              "width": 407,
              "height": 419
            },
            {
              "x": 152,
              "y": 1063,
              "width": 668,
              "height": 407
            }
          ]
        }
      ],
      "start": "01:50.9",
      "end": "02:02.7"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 840,
              "y": 1036,
              "width": 1029,
              "height": 399
            },
            {
              "x": 120,
              "y": 1479,
              "width": 581,
              "height": 407
            }
          ]
        }
      ],
      "start": "02:02.7",
      "end": "02:16.0"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 702,
              "y": 1495,
              "width": 1151,
              "height": 399
            }
          ]
        }
      ],
      "start": "02:16.0",
      "end": "02:26.8"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 132,
              "y": 1891,
              "width": 1729,
              "height": 518
            }
          ]
        }
      ],
      "start": "02:26.8",
      "end": "02:50.7"
    }
  ],
  "videoUrl": "https://www.youtube.com/watch?v=MswHKA4dako",
  "version": 1,
  "pageUrls": [
    "https://images2.imgbox.com/65/70/GUHRgkv7_o.jpg?download=true",
    "https://images2.imgbox.com/b6/c7/QJCUivyK_o.jpg?download=true"
  ]
}

=== stillwaiting/emptybars/composers/debussy/childrens-corner-2-jimbo/crossley/sections.json
{
  "sections": [
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 281,
              "y": 390,
              "width": 1312,
              "height": 439
            },
            {
              "x": 42,
              "y": 806,
              "width": 499,
              "height": 443
            }
          ]
        }
      ],
      "start": "02:21.5",
      "end": "02:37.5"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 604,
              "y": 928,
              "width": 945,
              "height": 343
            },
            {
              "x": 52,
              "y": 1272,
              "width": 661,
              "height": 452
            }
          ]
        }
      ],
      "start": "02:37.5",
      "end": "02:53.7"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 757,
              "y": 1292,
              "width": 753,
              "height": 386
            },
            {
              "x": 72,
              "y": 1765,
              "width": 360,
              "height": 370
            }
          ]
        }
      ],
      "start": "02:54.2",
      "end": "03:03.9"
    },
    {
      "pages": [
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 449,
              "y": 1781,
              "width": 1018,
              "height": 400
            }
          ]
        }
      ],
      "start": "03:03.9",
      "end": "03:16.0"
    },
    {
      "pages": [
        1,
        0
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 142,
              "y": 171,
              "width": 575,
              "height": 393
            }
          ]
        },
        {
          "pageIdx": 0,
          "areas": [
            {
              "x": 1408,
              "y": 1765,
              "width": 138,
              "height": 317
            }
          ]
        }
      ],
      "start": "03:16.0",
      "end": "03:22.5"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 710,
              "y": 155,
              "width": 856,
              "height": 439
            },
            {
              "x": 59,
              "y": 611,
              "width": 323,
              "height": 323
            }
          ]
        }
      ],
      "start": "03:22.5",
      "end": "03:32.5"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 400,
              "y": 595,
              "width": 1143,
              "height": 347
            }
          ]
        }
      ],
      "start": "03:32.5",
      "end": "03:44.9"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 95,
              "y": 988,
              "width": 1352,
              "height": 370
            }
          ]
        }
      ],
      "start": "03:44.9",
      "end": "03:55.2"
    },
    {
      "pages": [
        1
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 1441,
              "y": 1001,
              "width": 128,
              "height": 360
            },
            {
              "x": 92,
              "y": 1365,
              "width": 1497,
              "height": 396
            },
            {
              "x": 95,
              "y": 1742,
              "width": 700,
              "height": 403
            }
          ]
        }
      ],
      "start": "03:55.2",
      "end": "04:12.7"
    },
    {
      "pages": [
        1,
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 1,
          "areas": [
            {
              "x": 816,
              "y": 1788,
              "width": 753,
              "height": 386
            }
          ]
        },
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 82,
              "y": 138,
              "width": 773,
              "height": 449
            }
          ]
        }
      ],
      "start": "04:12.7",
      "end": "04:22.0"
    },
    {
      "pages": [
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 843,
              "y": 241,
              "width": 717,
              "height": 357
            },
            {
              "x": 79,
              "y": 598,
              "width": 766,
              "height": 347
            }
          ]
        }
      ],
      "start": "04:22.0",
      "end": "04:31.2"
    },
    {
      "pages": [
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 859,
              "y": 598,
              "width": 674,
              "height": 357
            }
          ]
        }
      ],
      "start": "04:31.2",
      "end": "04:36.0"
    },
    {
      "pages": [
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 76,
              "y": 988,
              "width": 1487,
              "height": 386
            },
            {
              "x": 109,
              "y": 1388,
              "width": 175,
              "height": 337
            }
          ]
        }
      ],
      "start": "04:36.0",
      "end": "04:47.0"
    },
    {
      "pages": [
        2
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 115,
              "y": 1375,
              "width": 1431,
              "height": 343
            }
          ]
        }
      ],
      "start": "04:46.5",
      "end": "04:56.2"
    },
    {
      "pages": [
        2,
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 2,
          "areas": [
            {
              "x": 105,
              "y": 1778,
              "width": 1408,
              "height": 383
            }
          ]
        },
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 72,
              "y": 168,
              "width": 750,
              "height": 429
            }
          ]
        }
      ],
      "start": "04:56.2",
      "end": "05:13.3"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 819,
              "y": 185,
              "width": 773,
              "height": 413
            },
            {
              "x": 99,
              "y": 575,
              "width": 700,
              "height": 380
            }
          ]
        }
      ],
      "start": "05:13.3",
      "end": "05:23.4"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 794,
              "y": 577,
              "width": 796,
              "height": 409
            },
            {
              "x": 97,
              "y": 981,
              "width": 492,
              "height": 363
            }
          ]
        }
      ],
      "start": "05:23.4",
      "end": "05:33.5"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 589,
              "y": 1014,
              "width": 955,
              "height": 363
            },
            {
              "x": 103,
              "y": 1381,
              "width": 340,
              "height": 376
            }
          ]
        }
      ],
      "start": "05:33.5",
      "end": "05:43.6"
    },
    {
      "pages": [
        3
      ],
      "pageAreas": [
        {
          "pageIdx": 3,
          "areas": [
            {
              "x": 87,
              "y": 1758,
              "width": 1454,
              "height": 413
            },
            {
              "x": 467,
              "y": 1368,
              "width": 1097,
              "height": 380
            }
          ]
        }
      ],
      "start": "05:43.6",
      "end": "05:53.6"
    }
  ],
  "videoUrl": "https://www.youtube.com/watch?v=1k_OLrK4ZuE?t=0.9",
  "version": 1,
  "pageUrls": [
    "https://images2.imgbox.com/6c/97/Yzd4DIGU_o.jpg?download=true",
    "https://images2.imgbox.com/64/92/pgnfik4q_o.jpg?download=true",
    "https://images2.imgbox.com/cb/aa/8rCzR3B2_o.jpg?download=true",
    "https://images2.imgbox.com/61/e7/kQuQbxaD_o.jpg?download=true"
  ]
}
